### ISSUE TITLE
Does pybiomart support v0.9 of Biomart?

### ISSUE THREAD

**Issue by uludag** [jrderuiter/pybiomart#3]
Hi,
I was trying to use pybiomart to call genenames.org [Biomart service](http://biomart.genenames.org/martservice/marts), however I was not able to construct a working pybam BiomartServer object.

```
from pybiomart import Server
server = Server(host='http://biomart.genenames.org', path="/martservice/results")
server.list_marts()
```

Is this because pybam is not supporting v0.9 of Biomart?

--mahmut

**Comment by jrderuiter** [comment]
The library is currently geared towards Biomart 0.8 (I think this is the version that Ensembl is using), which is probably why you are running into problems. I'll get back to you when I've had time to look into it!

**Comment by uludag** [comment]
Thanks Julian. No urgency on our side, for now I use  more generic libraries in [two simple Biomart scripts that given Ensembl gene ids return gene names and aliases](https://gist.github.com/uludag). I would like to try pybam when it supports Biomart 0.9.    --mahmut

**Comment by jrderuiter** [comment]
Unfortunately I don't have any time to work on this for the time being. If there is more general interest, we can consider re-opening the issue.
